name: Release nuget

on:
  push:
    tags: "Client-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          include-prerelease: true
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release

      - name: Create the package - Client
        run: dotnet pack --configuration Release MyPostgreSQL/MyPostgreSQL.csproj /p:Version=${GITHUB_REF#refs/tags/Client-}

      - name: Publish the package to GPR - Client
        run: dotnet nuget push MyPostgreSQL/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}